from setuptools import setup, find_packages

setup(
    name='SpatialBiologyToolkit',
    version='0.1',
    packages=['SpatialBiologyToolkit'],
    install_requires=[
        'anndata',
        'colorcet',
        'ipykernel',
        'ipython',
        'magicgui',
        'matplotlib',
        'napari',
        'networkx',
        'numpy',
        'pandas',
        'scanpy',
        'scikit-learn',
        'scikit-image',
        'scipy',
        'shapely',
        'sphinx',
        'seaborn',
        'setuptools',
        'statsmodels',
        'squidpy',
        'tifffile',
        'tqdm',
        'umap-learn',
        'vispy',
        'bbknn',
        'harmonypy',
        'sc3s',
        'ehrapy',
        'tensorflow'
    ],
    description='A tool kit for analysing high dimensional spatial data',
    author='Michael Haley',
    author_email='mrmichaelhaley@gmail.com',
    url='https://github.com/dr-michael-haley/imcanalysis',
)