prep=job_preprocess.sh
vis=job_visualisations.sh
nimbus=job_nimbus.sh
bint=job_batch_integration.sh
rapids=job_rapids.sh
cellvision=job_cellvision.sh
bbn=job_biobatchnet.sh
subcl=job_subclustering.sh
cchar=job_cellcharter.sh
starling=job_starling.sh
dnqc=job_denoising_qc.sh
aiinter=job_ai.sh
denoise=job_denoising.sh
config=job_config.sh
cellpose=job_cellposesam.sh
reint=job_reintegrate.sh
zipqc=job_zipqc.sh
scport=job_scport.sh
debug=job_debug.sh
pairsp=job_pairwise_spatial.sh
nxsp=job_networkx_spatial.sh
remap=job_remap_obs.sh
slogs=job_slurmlogs.sh
rebuildmeta=job_rebuild_metadata.sh
popqc=job_population_embedding_qc.sh
