prep=job_preprocess.sh
vis=job_visualisations.sh
nimbus=job_nimbus.sh
bint=job_batch_integration.sh
rapids=job_rapids.sh
cellvision-extract=job_cellvision_extract.sh
cellvision-embed=job_cellvision_embed.sh
cellvision-cluster=job_cellvision_cluster.sh
cellvision-plot=job_cellvision_plot.sh
cellvision-full=job_cellvision_full.sh
bbn=job_biobatchnet.sh
subcl=job_subclustering.sh
cchar=job_cellcharter.sh
starling=job_starling.sh
dnqc=job_denoising_qc.sh
aiinter=job_ai.sh
denoise=job_denoising.sh
config=job_config.sh
cellpose=job_cellposesam.sh
reint=job_reintegrate.sh
zipqc=job_zipqc.sh
scport=job_scport.sh
debug=job_debug.sh
pairsp=job_pairwise_spatial.sh
nxsp=job_networkx_spatial.sh
remap=job_remap_obs.sh
slogs=job_slurmlogs.sh
rebuildmeta=job_rebuild_metadata.sh
popqc=job_population_embedding_qc.sh
hyperstac-preprocess=job_hyperstac_preprocess.sh
hyperstac-model=job_hyperstac_model.sh
hyperstac-permutation=job_hyperstac_permutation.sh
hyperstac-visualise=job_hyperstac_visualise.sh
cox=job_cox_survival.sh
hyperstac-stability=job_hyperstac_stability.sh
hyperstac-full=job_hyperstac_full.sh
cellfeat=job_cell_features.sh
maxfuse=job_maxfuse.sh
spatialdata=job_spatialdata.sh
neighsig=job_neighbour_signal.sh
