"""
Napari active-learning QC tool for CellPose-SAM IMC segmentation masks.

What it does
------------
This viewer adds a safe object-level QC layer after CellPose-SAM segmentation.
It loads the precomputed per-cell feature table generated by
``SpatialBiologyToolkit/scripts/cellpose_sam.py``, lets a user stage good and
artifact mask labels, confirms staged labels into a reusable training set,
trains a lightweight tabular classifier, applies artifact-probability scores,
and exports cleaned masks without overwriting the original masks.

Expected inputs
---------------
* ``images``: by default an ``images`` folder. The preferred layout follows
  ``napari_imc_explorer``: ``images/<ROI>/<channel>.tiff``. A direct
  one-image-per-ROI layout such as ``images/<ROI>.tiff`` is also accepted.
* ``masks``: by default a ``masks`` folder with one TIFF mask per ROI, named
  ``<ROI>.tiff`` or ``<ROI>.tif``.
* Feature table: usually ``masks/CellposeSAM_cell_metrics.csv``.
* Feature dictionary: usually
  ``masks/CellposeSAM_cell_metrics_feature_dictionary.csv``.
* QC output folder: by default ``qc_classifier``.

Saved outputs
-------------
The tool writes resumable state under the QC output folder:

* ``labels/<ROI>_labels.csv``: confirmed and flagged object labels.
* ``scores/<ROI>_scores.csv``: artifact_probability scores.
* ``models/*.joblib`` and matching metadata JSON files.
* ``masks_cleaned/<ROI>_cleaned_mask.tiff``: exported cleaned masks.
* ``exports/<ROI>_cell_qc.csv``: per-cell audit tables.
* ``metadata/*.json`` and ``logs/qc_session_log.txt``.

Launch example
--------------
``python -m SpatialBiologyToolkit.napari_cellpose_qc_active_learning --masks masks --images images``

Score convention
----------------
``artifact_probability = 0`` means likely good cell.
``artifact_probability = 1`` means likely artifact.

Assumptions from repository inspection
--------------------------------------
The upstream CellPose-SAM metrics script uses ``ROI`` and ``ObjectNumber`` as
the canonical feature-row identifiers. Its feature dictionary is indexed by
``feature`` and includes ``type/source`` and ``description`` columns. This tool
uses the dictionary to select model inputs and excludes identifiers, metadata,
and segmentation-configuration columns unless a future dictionary explicitly
marks them as valid model inputs.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from types import SimpleNamespace

import napari
import numpy as np
import pandas as pd
from qtpy.QtCore import Qt
from qtpy.QtGui import QKeySequence
try:
    from qtpy.QtGui import QShortcut
except ImportError:
    from qtpy.QtWidgets import QShortcut
from qtpy.QtWidgets import (
    QCheckBox,
    QComboBox,
    QDockWidget,
    QDoubleSpinBox,
    QFileDialog,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListWidget,
    QListWidgetItem,
    QPushButton,
    QRadioButton,
    QButtonGroup,
    QSpinBox,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from .qc_classifier.export import (
    EXPORT_CLASSIFIER_THRESHOLD,
    EXPORT_COMBINED,
    EXPORT_CONFIRMED_AND_FLAGGED_ARTIFACTS,
    EXPORT_CONFIRMED_ARTIFACTS,
    export_cleaned_mask_and_table,
)
from .qc_classifier.feature_dictionary import load_feature_dictionary
from .qc_classifier.feature_table import (
    load_feature_table,
    select_model_features,
    validate_feature_inputs,
)
from .qc_classifier.io import (
    append_log,
    discover_roi_assets,
    ensure_output_structure,
    file_fingerprint,
    load_display_image,
    load_mask,
    read_json,
    timestamp_utc,
    write_json,
)
from .qc_classifier.labels import (
    CONFIRMED_ARTIFACT,
    CONFIRMED_GOOD,
    FLAGGED_ARTIFACT,
    FLAGGED_GOOD,
    RoiLabels,
    load_all_confirmed_labels,
    load_roi_labels,
    save_roi_labels,
)
from .qc_classifier.model import (
    load_model_bundle,
    save_model_bundle,
    score_feature_rows,
    train_classifier,
)
from .qc_classifier.napari_layers import (
    add_or_update_base_mask,
    add_or_update_label_state_layers,
    add_or_update_score_layer,
)
from .qc_classifier.scores import (
    load_roi_score_metadata,
    load_roi_scores,
    save_roi_scores,
    score_file_warnings,
)


def _as_list(value):
    if value is None:
        return []
    if isinstance(value, (list, tuple)):
        return [str(item) for item in value]
    return [str(value)]


def _set_combo_items(combo: QComboBox, items: list[str], current: str | None = None) -> None:
    combo.blockSignals(True)
    combo.clear()
    combo.addItems([str(item) for item in items])
    if current is not None:
        index = combo.findText(str(current))
        if index >= 0:
            combo.setCurrentIndex(index)
    combo.blockSignals(False)


def _build_dock_panel(widget_items) -> QWidget:
    panel = QWidget()
    layout = QVBoxLayout()
    layout.setContentsMargins(8, 8, 8, 8)
    panel.setLayout(layout)
    for item in widget_items:
        layout.addWidget(getattr(item, "native", item))
    layout.addStretch(1)
    return panel


def _browse_folder(target: QLineEdit) -> None:
    folder = QFileDialog.getExistingDirectory(None, "Select folder", target.text())
    if folder:
        target.setText(folder)


def _browse_file(target: QLineEdit, caption: str, filter_text: str) -> None:
    file_path, _ = QFileDialog.getOpenFileName(None, caption, target.text(), filter_text)
    if file_path:
        target.setText(file_path)


def _unique_mask_labels(mask: np.ndarray) -> set[int]:
    labels = np.unique(mask)
    return set(int(label) for label in labels if int(label) != 0)


def napari_cellpose_qc_active_learning(
    masks_folder: str = "masks",
    image_folders: str | list[str] = "images",
    feature_table_path: str | None = None,
    feature_dictionary_path: str | None = None,
    output_folder: str = "qc_classifier",
    roi_column: str = "ROI",
    object_column: str = "ObjectNumber",
    mask_extension: str | None = None,
    initial_roi: str | None = None,
    model_path: str | None = None,
) -> tuple[napari.Viewer, SimpleNamespace]:
    """
    Start the CellPose active-learning QC viewer.

    The viewer returns ``(viewer, handles)`` in the same spirit as
    ``napari_imc_explorer`` so notebooks can drive or inspect the UI.
    """

    masks_folder = str(masks_folder)
    image_folders = _as_list(image_folders)
    if feature_table_path is None:
        candidate = Path(masks_folder) / "CellposeSAM_cell_metrics.csv"
        feature_table_path = str(candidate) if candidate.exists() else ""
    if feature_dictionary_path is None:
        candidate = Path(masks_folder) / "CellposeSAM_cell_metrics_feature_dictionary.csv"
        feature_dictionary_path = str(candidate) if candidate.exists() else ""

    folders = ensure_output_structure(output_folder)

    viewer = napari.Viewer()

    state = SimpleNamespace(
        folders=folders,
        masks_folder=Path(masks_folder),
        image_folders=[Path(folder) for folder in image_folders],
        feature_table_path=Path(feature_table_path) if feature_table_path else None,
        feature_dictionary_path=Path(feature_dictionary_path) if feature_dictionary_path else None,
        feature_table=None,
        feature_dictionary=None,
        assets={},
        selected_features=[],
        dropped_features=[],
        selected_categories=[],
        current_roi=None,
        current_mask=None,
        current_labels=RoiLabels(""),
        current_scores=pd.DataFrame(),
        current_score_metadata={},
        model_bundle=None,
        dirty=False,
        undo_stack=[],
        warnings=[],
    )

    def _status(message: str) -> None:
        status_box.append(str(message))
        print(message)
        try:
            append_log(state.folders["root"], str(message))
        except Exception:
            pass

    def _set_model_status() -> None:
        if state.model_bundle is None:
            model_status_label.setText("Model: not loaded")
        else:
            model_status_label.setText(
                f"Model: {state.model_bundle.model_id} ({len(state.model_bundle.feature_columns)} features)"
            )

    def _analysis_rois() -> list[str]:
        feature_rois = set(state.feature_table.rois) if state.feature_table is not None else None
        rois = []
        for roi, assets in state.assets.items():
            if not assets.has_mask:
                continue
            if feature_rois is not None and roi not in feature_rois:
                continue
            rois.append(str(roi))
        return sorted(rois)

    def _labels_for_roi(roi: str) -> RoiLabels:
        if state.current_roi == roi:
            return state.current_labels
        try:
            return load_roi_labels(state.folders["labels"], roi)
        except Exception:
            return RoiLabels(str(roi))

    def _all_label_file_fingerprints() -> dict[str, dict]:
        label_folder = state.folders["labels"]
        if not label_folder.exists():
            return {}
        fingerprints = {}
        for path in sorted(label_folder.glob("*_labels.csv")):
            fingerprint = file_fingerprint(path)
            fingerprints[str(path)] = {
                "exists": fingerprint.get("exists", False),
                "size_bytes": fingerprint.get("size_bytes"),
                "sha256": fingerprint.get("sha256"),
            }
        return fingerprints

    def _flagged_label_count_anywhere(rois: list[str]) -> int:
        total = 0
        for roi in rois:
            labels = _labels_for_roi(roi)
            total += len(labels.ids(FLAGGED_GOOD)) + len(labels.ids(FLAGGED_ARTIFACT))
        return total

    def _classifier_freshness(rois: list[str]) -> tuple[str, str, bool]:
        if state.model_bundle is None:
            return "red", "No classifier is loaded.", False
        flagged_count = _flagged_label_count_anywhere(rois)
        if flagged_count > 0:
            return "orange", f"{flagged_count} flagged label(s) need confirmation before retraining.", False
        if state.dirty:
            return "orange", "Current ROI labels have unsaved changes.", False
        if state.selected_features and list(state.model_bundle.feature_columns) != list(state.selected_features):
            return "orange", "Selected feature set changed since this classifier was trained.", False

        model_fingerprints = state.model_bundle.metadata.get("label_file_fingerprints")
        if not model_fingerprints:
            return "orange", "Model has no label-file fingerprints; retrain to make freshness auditable.", False

        current_fingerprints = _all_label_file_fingerprints()
        if current_fingerprints != model_fingerprints:
            return "orange", "Confirmed label files changed since this classifier was trained.", False

        return "green", "Classifier matches the confirmed labels on disk.", True

    def _score_matches_current_model(self_roi: str) -> bool:
        if state.model_bundle is None:
            return False
        score_metadata = (
            state.current_score_metadata
            if self_roi == state.current_roi
            else load_roi_score_metadata(state.folders["metadata"], self_roi)
        )
        return (
            bool(score_metadata)
            and score_metadata.get("model_id") == state.model_bundle.metadata.get("model_id")
            and score_metadata.get("feature_set_hash") == state.model_bundle.metadata.get("feature_set_hash")
        )

    def _review_metadata_path(roi: str) -> Path:
        return state.folders["metadata"] / f"{roi}_review_metadata.json"

    def _mark_current_roi_reviewed() -> None:
        if not state.current_roi or state.model_bundle is None:
            return
        if not _score_matches_current_model(state.current_roi):
            return
        write_json(
            _review_metadata_path(state.current_roi),
            {
                "roi": state.current_roi,
                "reviewed_at": timestamp_utc(),
                "model_id": state.model_bundle.metadata.get("model_id"),
                "feature_set_hash": state.model_bundle.metadata.get("feature_set_hash"),
                "score_file_current": True,
            },
        )

    def _review_matches_current_model(roi: str) -> bool:
        if state.model_bundle is None or not _score_matches_current_model(roi):
            return False
        review_metadata = read_json(_review_metadata_path(roi), default={}) or {}
        return (
            review_metadata.get("model_id") == state.model_bundle.metadata.get("model_id")
            and review_metadata.get("feature_set_hash") == state.model_bundle.metadata.get("feature_set_hash")
        )

    def _traffic_level_for_progress(completed: int, total: int) -> str:
        if total <= 0 or completed <= 0:
            return "red"
        if completed >= total:
            return "green"
        return "orange"

    def _set_traffic_light(key: str, level: str, text: str) -> None:
        label = traffic_light_labels.get(key)
        if label is None:
            return
        colours = {
            "green": ("#1b7f3a", "#ffffff"),
            "orange": ("#d98200", "#111111"),
            "red": ("#b3261e", "#ffffff"),
        }
        background, foreground = colours[level]
        label.setText(text)
        label.setStyleSheet(
            "QLabel {"
            f"background-color: {background};"
            f"color: {foreground};"
            "border-radius: 4px;"
            "padding: 7px;"
            "font-weight: 600;"
            "}"
        )

    def _update_traffic_lights(rois: list[str], classifier_is_fresh: bool, classifier_message: str, classifier_level: str) -> None:
        total_rois = len(rois)
        flagged_count = _flagged_label_count_anywhere(rois)
        _set_traffic_light(
            "flagged",
            "green" if flagged_count == 0 else "orange",
            f"Flagged labels pending confirmation: {flagged_count}",
        )
        _set_traffic_light("classifier", classifier_level, f"Classifier freshness: {classifier_message}")

        current_score_matches = bool(state.current_roi and _score_matches_current_model(state.current_roi))
        if not state.current_roi:
            current_roi_level = "red"
            current_roi_text = "Current ROI score: no ROI loaded"
        elif current_score_matches and classifier_is_fresh:
            current_roi_level = "green"
            current_roi_text = "Current ROI score: current classifier"
        elif current_score_matches:
            current_roi_level = "orange"
            current_roi_text = "Current ROI score: matches loaded model, but retraining is pending"
        else:
            current_roi_level = "red"
            current_roi_text = "Current ROI score: not run with current classifier"
        _set_traffic_light("current_roi_score", current_roi_level, current_roi_text)

        scored_rois = sum(1 for roi in rois if _score_matches_current_model(roi))
        _set_traffic_light(
            "all_scored",
            _traffic_level_for_progress(scored_rois, total_rois),
            f"Current classifier applied to ROIs: {scored_rois}/{total_rois}",
        )

        pos_neg_rois = 0
        for roi in rois:
            labels = _labels_for_roi(roi)
            if labels.ids(CONFIRMED_GOOD) and labels.ids(CONFIRMED_ARTIFACT):
                pos_neg_rois += 1
        _set_traffic_light(
            "all_pos_neg",
            _traffic_level_for_progress(pos_neg_rois, total_rois),
            f"ROIs with confirmed good and artifact labels: {pos_neg_rois}/{total_rois}",
        )

        reviewed_rois = sum(1 for roi in rois if _review_matches_current_model(roi))
        _set_traffic_light(
            "all_reviewed",
            _traffic_level_for_progress(reviewed_rois, total_rois),
            f"ROIs reviewed with current classifier: {reviewed_rois}/{total_rois}",
        )

    def _selected_categories_from_widget() -> list[str]:
        categories = []
        for index in range(category_list.count()):
            item = category_list.item(index)
            if item.checkState() == Qt.Checked:
                categories.append(item.text())
        return categories

    def _refresh_feature_selection() -> None:
        state.selected_categories = _selected_categories_from_widget()
        if state.feature_table is None or state.feature_dictionary is None:
            state.selected_features = []
            state.dropped_features = []
            feature_count_label.setText("Selected features: 0")
            return
        selected, dropped, warnings = select_model_features(
            state.feature_table,
            state.feature_dictionary,
            categories=state.selected_categories,
        )
        state.selected_features = selected
        state.dropped_features = dropped
        feature_count_label.setText(f"Selected features: {len(selected)}")
        if warnings:
            state.warnings = warnings
        try:
            _update_status_summary()
        except NameError:
            pass

    def _refresh_category_widget() -> None:
        category_list.clear()
        if state.feature_dictionary is None:
            return

        eligible = state.feature_dictionary.eligible_feature_names(categories=None)
        eligible_categories = {state.feature_dictionary.category_for(feature) for feature in eligible}
        for category in state.feature_dictionary.categories:
            item = QListWidgetItem(str(category))
            item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
            item.setCheckState(Qt.Checked if category in eligible_categories else Qt.Unchecked)
            category_list.addItem(item)
        _refresh_feature_selection()

    def _load_inputs_from_controls() -> None:
        state.masks_folder = Path(masks_folder_input.text())
        state.image_folders = [Path(folder.strip()) for folder in images_folder_input.text().split(";") if folder.strip()]
        state.feature_table_path = Path(feature_table_input.text()) if feature_table_input.text().strip() else None
        state.feature_dictionary_path = Path(feature_dictionary_input.text()) if feature_dictionary_input.text().strip() else None
        state.folders = ensure_output_structure(output_folder_input.text())

        state.feature_table = None
        state.feature_dictionary = None
        state.warnings = []

        if state.feature_table_path and state.feature_table_path.exists():
            try:
                state.feature_table = load_feature_table(
                    state.feature_table_path,
                    roi_column=roi_column_input.text().strip() or roi_column,
                    object_column=object_column_input.text().strip() or object_column,
                )
                _status(f"Loaded feature table: {state.feature_table_path}")
            except Exception as exc:
                _status(f"Could not load feature table: {exc}")
        else:
            _status("Feature table is not set or does not exist.")

        if state.feature_dictionary_path and state.feature_dictionary_path.exists():
            try:
                state.feature_dictionary = load_feature_dictionary(state.feature_dictionary_path)
                _status(f"Loaded feature dictionary: {state.feature_dictionary_path}")
            except Exception as exc:
                _status(f"Could not load feature dictionary: {exc}")
        else:
            _status("Feature dictionary is not set or does not exist.")

        feature_rois = state.feature_table.rois if state.feature_table is not None else None
        state.assets = discover_roi_assets(
            state.masks_folder,
            state.image_folders,
            feature_rois=feature_rois,
            mask_extension=mask_extension,
        )
        rois = sorted(state.assets)
        _set_combo_items(roi_selector, rois, current=state.current_roi or initial_roi)
        _refresh_category_widget()
        _update_image_channel_choices()
        _update_status_summary()

    def _update_image_channel_choices() -> None:
        roi = str(roi_selector.currentText()) if roi_selector.currentText() else state.current_roi
        image_paths = state.assets.get(roi).image_paths if roi in state.assets else {}
        preferred_channel = _preferred_image_channel(image_paths or {})
        _set_combo_items(image_channel_selector, sorted(image_paths or {}), current=preferred_channel)

    def _preferred_image_channel(image_paths: dict[str, Path]) -> str | None:
        """Prefer DNA channels for the default ROI image."""

        if not image_paths:
            return None
        sorted_channels = sorted(image_paths)
        for channel_name in sorted_channels:
            if _is_dna_channel(channel_name, image_paths[channel_name]):
                return channel_name
        return sorted_channels[0]

    def _is_dna_channel(channel_name: str, image_path: Path | None = None) -> bool:
        image_path_text = "" if image_path is None else Path(image_path).name.lower()
        return "dna" in str(channel_name).lower() or "dna" in image_path_text

    def _current_feature_rows() -> pd.DataFrame:
        if state.feature_table is None or state.current_roi is None:
            return pd.DataFrame()
        return state.feature_table.rows_for_roi(state.current_roi)

    def _save_current_roi_state() -> None:
        if not state.current_roi:
            return
        path = save_roi_labels(state.folders["labels"], state.current_labels)
        assets = state.assets.get(state.current_roi)
        metadata = {
            "roi": state.current_roi,
            "label_file": str(path),
            "saved_at": timestamp_utc(),
            "mask_path": None if assets is None or assets.mask_path is None else str(assets.mask_path),
            "image_paths": {} if assets is None or not assets.image_paths else {k: str(v) for k, v in assets.image_paths.items()},
            "feature_table": file_fingerprint(state.feature_table_path, max_bytes=1024 * 1024),
            "feature_dictionary": file_fingerprint(state.feature_dictionary_path, max_bytes=1024 * 1024),
            "selected_feature_count": len(state.selected_features),
            "selected_feature_categories": state.selected_categories,
        }
        write_json(state.folders["metadata"] / f"{state.current_roi}_metadata.json", metadata)
        state.dirty = False
        _update_status_summary()
        _status(f"Saved labels for ROI '{state.current_roi}' to {path}.")

    def _load_saved_current_roi_state() -> None:
        if not state.current_roi:
            return
        state.current_labels = load_roi_labels(state.folders["labels"], state.current_roi)
        if state.current_mask is not None:
            add_or_update_label_state_layers(
                viewer,
                state.current_mask,
                state.current_labels,
                contours=_label_contours_from_widgets(),
            )
        state.dirty = False
        _update_status_summary()
        _status(f"Reloaded labels for ROI '{state.current_roi}'.")

    def _initial_label_layer_visibilities() -> dict[str, bool]:
        return {
            CONFIRMED_GOOD: confirmed_layers_visible_checkbox.isChecked(),
            CONFIRMED_ARTIFACT: confirmed_layers_visible_checkbox.isChecked(),
            FLAGGED_GOOD: flagged_layers_visible_checkbox.isChecked(),
            FLAGGED_ARTIFACT: flagged_layers_visible_checkbox.isChecked(),
        }

    def _load_image_layers(roi: str, *, all_images: bool = False) -> None:
        assets = state.assets.get(roi)
        image_paths = assets.image_paths if assets is not None and assets.image_paths else {}
        if not image_paths:
            _status(f'No images found for ROI "{roi}".')
            return

        if all_images:
            selected_items = list(image_paths.items())
        else:
            selected_channel = image_channel_selector.currentText()
            if selected_channel and selected_channel in image_paths:
                selected_items = [(selected_channel, image_paths[selected_channel])]
            else:
                preferred_channel = _preferred_image_channel(image_paths)
                selected_items = [(preferred_channel, image_paths[preferred_channel])]

        for channel_name, image_path in selected_items:
            try:
                image, is_rgb = load_display_image(
                    image_path,
                    quantile=quantile_spin.value(),
                    minimum_pixel_counts=min_pixel_spin.value(),
                )
                layer_name = f"{channel_name}::{roi}" if all_images else str(channel_name)
                layer = viewer.add_image(
                    image,
                    name=layer_name,
                    rgb=is_rgb,
                    blending="additive",
                    colormap="gray" if not is_rgb else None,
                    visible=(
                        dna_layer_visible_checkbox.isChecked()
                        if _is_dna_channel(channel_name, image_path)
                        else (not all_images or len(selected_items) == 1)
                    ),
                )
                if state.current_mask is not None and image.ndim >= 2 and image.shape[:2] != state.current_mask.shape:
                    _status(
                        f"Image/mask shape mismatch for '{channel_name}' in ROI '{roi}': "
                        f"image {image.shape[:2]} vs mask {state.current_mask.shape}."
                    )
            except Exception as exc:
                _status(f"Could not load image '{image_path}': {exc}")

    def _load_roi(roi: str | None = None) -> None:
        if state.current_roi and state.dirty:
            _save_current_roi_state()

        roi = str(roi or roi_selector.currentText())
        if not roi:
            _status("No ROI selected.")
            return
        if roi not in state.assets:
            _status(f"ROI '{roi}' is not available.")
            return

        assets = state.assets[roi]
        if not assets.has_mask:
            _status(f"ROI '{roi}' has no mask file.")
            return

        viewer.layers.select_all()
        viewer.layers.remove_selected()

        state.current_roi = roi
        roi_selector.setCurrentText(roi)
        _update_image_channel_choices()

        try:
            state.current_mask = load_mask(assets.mask_path)
        except Exception as exc:
            _status(f"Could not load mask for ROI '{roi}': {exc}")
            return

        _load_image_layers(roi, all_images=False)
        add_or_update_base_mask(
            viewer,
            state.current_mask,
            visible=all_cells_layer_visible_checkbox.isChecked(),
        )

        state.current_labels = load_roi_labels(state.folders["labels"], roi)
        add_or_update_label_state_layers(
            viewer,
            state.current_mask,
            state.current_labels,
            contours=_label_contours_from_widgets(),
            visibilities=_initial_label_layer_visibilities(),
        )

        state.current_scores = load_roi_scores(state.folders["scores"], roi)
        state.current_score_metadata = load_roi_score_metadata(state.folders["metadata"], roi)
        stale_warnings = score_file_warnings(
            state.current_score_metadata,
            None if state.model_bundle is None else state.model_bundle.metadata,
        )
        for warning in stale_warnings:
            _status(f"WARNING: {warning}")
        add_or_update_score_layer(
            viewer,
            state.current_mask,
            state.current_scores,
            visible=probability_layer_visible_checkbox.isChecked() and not state.current_scores.empty,
        )
        _mark_current_roi_reviewed()

        mask_labels = _unique_mask_labels(state.current_mask)
        feature_labels = state.feature_table.object_ids_for_roi(roi) if state.feature_table is not None else set()
        if feature_labels:
            missing_features = mask_labels - feature_labels
            missing_masks = feature_labels - mask_labels
            if missing_features:
                _status(f"WARNING: ROI '{roi}' has {len(missing_features)} mask labels without feature rows.")
            if missing_masks:
                _status(f"WARNING: ROI '{roi}' has {len(missing_masks)} feature rows without mask labels.")

        state.undo_stack.clear()
        state.dirty = False
        _update_status_summary()
        _status(f"Loaded ROI '{roi}'.")

    def _previous_roi() -> None:
        rois = [roi_selector.itemText(index) for index in range(roi_selector.count())]
        if not rois:
            return
        current = rois.index(state.current_roi) if state.current_roi in rois else max(roi_selector.currentIndex(), 0)
        _load_roi(rois[(current - 1) % len(rois)])

    def _next_roi() -> None:
        rois = [roi_selector.itemText(index) for index in range(roi_selector.count())]
        if not rois:
            return
        current = rois.index(state.current_roi) if state.current_roi in rois else max(roi_selector.currentIndex(), 0)
        _load_roi(rois[(current + 1) % len(rois)])

    def _push_undo() -> None:
        state.undo_stack.append(state.current_labels.clone())
        if len(state.undo_stack) > 50:
            state.undo_stack.pop(0)

    def _label_contours_from_widgets() -> dict[str, int]:
        return {
            CONFIRMED_GOOD: confirmed_good_contour_spin.value(),
            CONFIRMED_ARTIFACT: confirmed_artifact_contour_spin.value(),
            FLAGGED_GOOD: flagged_good_contour_spin.value(),
            FLAGGED_ARTIFACT: flagged_artifact_contour_spin.value(),
        }

    def _set_annotation_mode(mode: str) -> None:
        button = annotation_mode_buttons.get(mode)
        if button is None:
            return
        button.setChecked(True)
        clicked_cell_label.setText(f"Annotation mode: {mode}")

    def _apply_annotation_shortcuts(silent: bool = False) -> None:
        shortcut_parent = getattr(viewer.window, "_qt_window", None) or annotation_mode_widget
        for mode, input_widget in annotation_shortcut_inputs.items():
            shortcut_text = input_widget.text().strip()
            key_sequence = QKeySequence(shortcut_text)
            shortcut = annotation_shortcuts.get(mode)
            if shortcut is None:
                shortcut = QShortcut(key_sequence, shortcut_parent)
                shortcut.activated.connect(lambda mode=mode: _set_annotation_mode(mode))
                annotation_shortcuts[mode] = shortcut
            shortcut.setKey(key_sequence)
            shortcut.setEnabled(bool(shortcut_text))
        if not silent:
            _status("Updated annotation mode shortcuts.")

    def _update_label_layers_display() -> None:
        if state.current_mask is not None:
            add_or_update_label_state_layers(
                viewer,
                state.current_mask,
                state.current_labels,
                contours=_label_contours_from_widgets(),
            )

    def _refresh_label_layers() -> None:
        if state.current_mask is not None:
            add_or_update_label_state_layers(
                viewer,
                state.current_mask,
                state.current_labels,
                contours=_label_contours_from_widgets(),
            )
        state.dirty = True
        _update_status_summary()

    def _annotate_object(object_id: int, *, source: str = "manual") -> None:
        mode = annotation_mode_group.checkedButton().text()
        if object_id <= 0:
            clicked_cell_label.setText("Clicked cell: background")
            return

        current_score = None
        if not state.current_scores.empty and "ObjectNumber" in state.current_scores.columns:
            score_rows = state.current_scores[pd.to_numeric(state.current_scores["ObjectNumber"], errors="coerce") == object_id]
            if not score_rows.empty:
                current_score = float(score_rows.iloc[0]["artifact_probability"])

        clicked_cell_label.setText(
            f"Clicked cell: ROI={state.current_roi}, ObjectNumber={object_id}, "
            f"score={'NA' if current_score is None else f'{current_score:.3f}'}, "
            f"state={state.current_labels.state_for(object_id) or 'none'}"
        )

        if mode == "inspect only":
            return

        _push_undo()
        changed = False
        if mode == "flag as good":
            changed = state.current_labels.set_state(object_id, FLAGGED_GOOD, source=source)
        elif mode == "flag as artifact":
            changed = state.current_labels.set_state(object_id, FLAGGED_ARTIFACT, source=source)
        elif mode == "erase flagged label":
            changed = state.current_labels.remove_flagged(object_id)
        elif mode == "remove any label":
            changed = state.current_labels.remove_any(object_id)

        if changed:
            _refresh_label_layers()

    def _viewer_click_callback(viewer_obj, event) -> None:
        if state.current_mask is None or event.type != "mouse_press" or event.button != 1:
            return
        position = event.position
        if len(position) < 2:
            return
        row = int(round(position[-2]))
        col = int(round(position[-1]))
        if row < 0 or col < 0 or row >= state.current_mask.shape[0] or col >= state.current_mask.shape[1]:
            return
        object_id = int(state.current_mask[row, col])
        _annotate_object(object_id)

    viewer.mouse_drag_callbacks.append(_viewer_click_callback)

    def _confirm_flagged() -> None:
        _push_undo()
        count = state.current_labels.confirm_flagged()
        _refresh_label_layers()
        _save_current_roi_state()
        _status(f"Confirmed {count} flagged label(s) for ROI '{state.current_roi}'.")

    def _clear_flagged() -> None:
        _push_undo()
        count = state.current_labels.clear_flagged()
        _refresh_label_layers()
        _save_current_roi_state()
        _status(f"Cleared {count} flagged label(s) for ROI '{state.current_roi}'.")

    def _undo_last_annotation() -> None:
        if not state.undo_stack:
            _status("No annotation action to undo.")
            return
        state.current_labels = state.undo_stack.pop()
        _refresh_label_layers()
        _status("Undid last annotation change.")

    def _bulk_flag(target_state: str) -> None:
        if state.current_scores.empty:
            _status("No score file is loaded for this ROI.")
            return
        if "ObjectNumber" not in state.current_scores.columns or "artifact_probability" not in state.current_scores.columns:
            _status("Score table must contain ObjectNumber and artifact_probability columns.")
            return

        scores = state.current_scores.copy()
        scores["artifact_probability"] = pd.to_numeric(scores["artifact_probability"], errors="coerce")
        scores["ObjectNumber"] = pd.to_numeric(scores["ObjectNumber"], errors="coerce")
        scores = scores.dropna(subset=["ObjectNumber", "artifact_probability"])

        if target_state == FLAGGED_GOOD:
            candidates = scores[scores["artifact_probability"] <= lower_threshold_spin.value()]
            candidates = candidates.sort_values("artifact_probability", ascending=True)
        else:
            candidates = scores[scores["artifact_probability"] >= upper_threshold_spin.value()]
            candidates = candidates.sort_values("artifact_probability", ascending=False)

        selected_ids = []
        for object_id in candidates["ObjectNumber"].astype(int).tolist():
            current_state = state.current_labels.state_for(object_id)
            if avoid_confirmed_checkbox.isChecked() and current_state in {CONFIRMED_GOOD, CONFIRMED_ARTIFACT}:
                continue
            if exclude_flagged_checkbox.isChecked() and current_state in {FLAGGED_GOOD, FLAGGED_ARTIFACT}:
                continue
            selected_ids.append(object_id)
            if max_bulk_spin.value() > 0 and len(selected_ids) >= max_bulk_spin.value():
                break

        _push_undo()
        changed = 0
        for object_id in selected_ids:
            if state.current_labels.set_state(object_id, target_state, source="threshold-assisted"):
                changed += 1
        _refresh_label_layers()
        _status(f"Flagged {changed} cell(s) as {target_state.replace('_', ' ')}.")

    def _validate_inputs() -> None:
        _refresh_feature_selection()
        if state.feature_table is None or state.feature_dictionary is None:
            _status("Load both a feature table and feature dictionary before validation.")
            return

        mask_labels_by_roi = {}
        for roi, assets in state.assets.items():
            if not assets.has_mask:
                continue
            try:
                mask_labels_by_roi[roi] = _unique_mask_labels(load_mask(assets.mask_path))
            except Exception as exc:
                _status(f"Could not validate mask labels for ROI '{roi}': {exc}")

        report = validate_feature_inputs(
            state.feature_table,
            state.feature_dictionary,
            categories=state.selected_categories,
            roi_assets=state.assets,
            mask_labels_by_roi=mask_labels_by_roi,
        )
        for message in report.messages():
            _status(message)
        if report.ok:
            _status(f"Validation complete. Selected {len(report.selected_features)} model feature(s).")

    def _load_previous_model() -> None:
        selected_path = model_file_input.text().strip()
        if not selected_path:
            candidate = state.folders["models"] / "classifier_latest.joblib"
            selected_path = str(candidate)
        model_file = Path(selected_path)
        if not model_file.exists():
            file_path, _ = QFileDialog.getOpenFileName(
                None,
                "Select saved model",
                str(state.folders["models"]),
                "Joblib models (*.joblib);;All files (*)",
            )
            if not file_path:
                return
            model_file = Path(file_path)
            model_file_input.setText(str(model_file))
        try:
            state.model_bundle = load_model_bundle(model_file)
            _set_model_status()
            _update_status_summary()
            _status(f"Loaded model: {model_file}")
        except Exception as exc:
            _status(f"Could not load model: {exc}")

    def _train_model() -> None:
        _save_current_roi_state()
        _refresh_feature_selection()
        if state.feature_table is None or state.feature_dictionary is None:
            _status("Load feature table and dictionary before training.")
            return
        if not state.selected_features:
            _status("No selected features are available for training.")
            return

        confirmed = load_all_confirmed_labels(state.folders["labels"])
        result = train_classifier(
            state.feature_table,
            confirmed,
            state.selected_features,
            model_type=model_type_combo.currentText(),
            feature_table_path=state.feature_table_path,
            dictionary_path=state.feature_dictionary_path,
            selected_categories=state.selected_categories,
        )
        for warning in result.warnings:
            _status(f"WARNING: {warning}")
        for error in result.errors:
            _status(f"ERROR: {error}")
        if not result.ok:
            return

        state.model_bundle = result.bundle
        state.model_bundle.metadata["feature_dictionary_selection"] = state.feature_dictionary.to_metadata(
            state.selected_categories,
            state.selected_features,
        )
        state.model_bundle.metadata["label_file_fingerprints"] = _all_label_file_fingerprints()
        model_path_saved, metadata_path = save_model_bundle(state.model_bundle, state.folders["models"], make_latest=True)
        model_file_input.setText(str(model_path_saved))
        _set_model_status()
        _update_status_summary()
        _status(
            f"Trained model on {state.model_bundle.metadata['training_example_count']} examples "
            f"({state.model_bundle.metadata['confirmed_good_count']} good, "
            f"{state.model_bundle.metadata['confirmed_artifact_count']} artifact)."
        )
        _status(f"Saved model metadata: {metadata_path}")

    def _apply_model_to_roi(roi: str) -> pd.DataFrame | None:
        if state.model_bundle is None:
            _status("Load or train a model before applying scores.")
            return None
        if state.feature_table is None:
            _status("Load a feature table before applying scores.")
            return None
        rows = state.feature_table.rows_for_roi(roi)
        if rows.empty:
            _status(f"ROI '{roi}' has no feature rows.")
            return None
        try:
            scores = score_feature_rows(state.model_bundle, state.feature_table, roi=roi)
        except Exception as exc:
            _status(f"Could not score ROI '{roi}': {exc}")
            return None
        save_roi_scores(
            state.folders["scores"],
            state.folders["metadata"],
            roi,
            scores,
            model_metadata=state.model_bundle.metadata,
        )
        return scores

    def _apply_model_current_roi() -> None:
        if not state.current_roi:
            _status("No ROI is loaded.")
            return
        scores = _apply_model_to_roi(state.current_roi)
        if scores is None:
            return
        state.current_scores = scores
        state.current_score_metadata = load_roi_score_metadata(state.folders["metadata"], state.current_roi)
        if state.current_mask is not None:
            add_or_update_score_layer(
                viewer,
                state.current_mask,
                state.current_scores,
                visible=probability_layer_visible_checkbox.isChecked(),
            )
        _mark_current_roi_reviewed()
        _update_status_summary()
        _status(f"Applied model to ROI '{state.current_roi}'.")

    def _apply_model_all_rois() -> None:
        if state.model_bundle is None or state.feature_table is None:
            _status("Load feature table and model before scoring all ROIs.")
            return
        scored = 0
        for roi in state.feature_table.rois:
            if _apply_model_to_roi(roi) is not None:
                scored += 1
        if state.current_roi:
            state.current_scores = load_roi_scores(state.folders["scores"], state.current_roi)
            state.current_score_metadata = load_roi_score_metadata(state.folders["metadata"], state.current_roi)
            if state.current_mask is not None:
                add_or_update_score_layer(
                    viewer,
                    state.current_mask,
                    state.current_scores,
                    visible=probability_layer_visible_checkbox.isChecked(),
                )
            _mark_current_roi_reviewed()
        _update_status_summary()
        _status(f"Applied model to {scored} ROI(s).")

    def _save_model() -> None:
        if state.model_bundle is None:
            _status("No model is loaded.")
            return
        model_path_saved, metadata_path = save_model_bundle(state.model_bundle, state.folders["models"], make_latest=True)
        model_file_input.setText(str(model_path_saved))
        _status(f"Saved model: {model_path_saved}")
        _status(f"Saved model metadata: {metadata_path}")

    def _export_current_roi() -> None:
        if not state.current_roi or state.current_mask is None:
            _status("No ROI is loaded.")
            return
        feature_rows = _current_feature_rows()
        if feature_rows.empty:
            _status(f"ROI '{state.current_roi}' has no feature rows; export cancelled.")
            return
        result = export_cleaned_mask_and_table(
            roi=state.current_roi,
            mask=state.current_mask,
            feature_rows=feature_rows.rename(columns={state.feature_table.object_column: "ObjectNumber"})
            if state.feature_table is not None else feature_rows,
            labels=state.current_labels,
            scores=state.current_scores,
            output_folder=state.folders["root"],
            rule=export_rule_combo.currentText(),
            threshold=export_threshold_spin.value(),
            feature_columns=state.selected_features,
            model_metadata=None if state.model_bundle is None else state.model_bundle.metadata,
            relabel=relabel_export_checkbox.isChecked(),
        )
        _status(f"Exported cleaned mask for ROI '{state.current_roi}': {result['cleaned_mask']}")

    def _export_all_rois() -> None:
        exported = 0
        if state.feature_table is None:
            _status("Load a feature table before exporting all ROIs.")
            return
        for roi, assets in state.assets.items():
            if not assets.has_mask:
                continue
            feature_rows = state.feature_table.rows_for_roi(roi)
            if feature_rows.empty:
                continue
            labels = load_roi_labels(state.folders["labels"], roi)
            scores = load_roi_scores(state.folders["scores"], roi)
            try:
                mask = load_mask(assets.mask_path)
                export_cleaned_mask_and_table(
                    roi=roi,
                    mask=mask,
                    feature_rows=feature_rows.rename(columns={state.feature_table.object_column: "ObjectNumber"}),
                    labels=labels,
                    scores=scores,
                    output_folder=state.folders["root"],
                    rule=export_rule_combo.currentText(),
                    threshold=export_threshold_spin.value(),
                    feature_columns=state.selected_features,
                    model_metadata=None if state.model_bundle is None else state.model_bundle.metadata,
                    relabel=relabel_export_checkbox.isChecked(),
                )
                exported += 1
            except Exception as exc:
                _status(f"Could not export ROI '{roi}': {exc}")
        _status(f"Exported cleaned masks for {exported} ROI(s).")

    def _update_status_summary() -> None:
        roi = state.current_roi or "none"
        rois = _analysis_rois()
        mask_count = int(np.max(state.current_mask)) if state.current_mask is not None and state.current_mask.size else 0
        feature_rows = len(_current_feature_rows()) if state.feature_table is not None and state.current_roi else 0
        counts = state.current_labels.counts() if state.current_labels is not None else {}
        score_status = "loaded" if state.current_scores is not None and not state.current_scores.empty else "not loaded"
        selected_feature_count = len(state.selected_features)
        classifier_level, classifier_message, classifier_is_fresh = _classifier_freshness(rois)
        summary_label.setText(
            "\n".join(
                [
                    f"Current ROI: {roi}",
                    f"ROIs in QC set: {len(rois)}",
                    f"Objects in mask: {mask_count}",
                    f"Feature rows for ROI: {feature_rows}",
                    f"Confirmed good: {counts.get(CONFIRMED_GOOD, 0)}",
                    f"Confirmed artifacts: {counts.get(CONFIRMED_ARTIFACT, 0)}",
                    f"Flagged good: {counts.get(FLAGGED_GOOD, 0)}",
                    f"Flagged artifacts: {counts.get(FLAGGED_ARTIFACT, 0)}",
                    f"Scores: {score_status}",
                    f"Selected features: {selected_feature_count}",
                ]
            )
        )
        _update_traffic_lights(rois, classifier_is_fresh, classifier_message, classifier_level)
        _set_model_status()

    # File/ROI controls
    masks_folder_input = QLineEdit(masks_folder)
    browse_masks_button = QPushButton("Browse masks")
    browse_masks_button.clicked.connect(lambda: _browse_folder(masks_folder_input))

    images_folder_input = QLineEdit(";".join(image_folders))
    browse_images_button = QPushButton("Browse images")
    browse_images_button.clicked.connect(lambda: _browse_folder(images_folder_input))

    feature_table_input = QLineEdit(str(feature_table_path or ""))
    browse_feature_table_button = QPushButton("Browse feature table")
    browse_feature_table_button.clicked.connect(
        lambda: _browse_file(feature_table_input, "Select feature table", "Tables (*.csv *.parquet *.pq);;All files (*)")
    )

    feature_dictionary_input = QLineEdit(str(feature_dictionary_path or ""))
    browse_feature_dictionary_button = QPushButton("Browse feature dictionary")
    browse_feature_dictionary_button.clicked.connect(
        lambda: _browse_file(feature_dictionary_input, "Select feature dictionary", "CSV files (*.csv);;All files (*)")
    )

    output_folder_input = QLineEdit(str(output_folder))
    browse_output_button = QPushButton("Browse output")
    browse_output_button.clicked.connect(lambda: _browse_folder(output_folder_input))

    roi_column_input = QLineEdit(roi_column)
    object_column_input = QLineEdit(object_column)
    reload_inputs_button = QPushButton("Load/reload inputs")
    reload_inputs_button.clicked.connect(_load_inputs_from_controls)

    roi_selector = QComboBox()
    roi_selector.currentTextChanged.connect(lambda _text: _update_image_channel_choices())
    previous_roi_button = QPushButton("Previous ROI")
    previous_roi_button.clicked.connect(_previous_roi)
    next_roi_button = QPushButton("Next ROI")
    next_roi_button.clicked.connect(_next_roi)
    load_roi_button = QPushButton("Load ROI")
    load_roi_button.clicked.connect(lambda: _load_roi())
    save_roi_button = QPushButton("Save current ROI state")
    save_roi_button.clicked.connect(_save_current_roi_state)
    reload_roi_state_button = QPushButton("Reload saved ROI state")
    reload_roi_state_button.clicked.connect(_load_saved_current_roi_state)

    image_channel_selector = QComboBox()
    load_selected_image_button = QPushButton("Add selected image")
    load_selected_image_button.clicked.connect(lambda: _load_image_layers(state.current_roi, all_images=False) if state.current_roi else None)
    load_all_images_button = QPushButton("Add all ROI images")
    load_all_images_button.clicked.connect(lambda: _load_image_layers(state.current_roi, all_images=True) if state.current_roi else None)
    quantile_spin = QDoubleSpinBox()
    quantile_spin.setRange(0.0, 1.0)
    quantile_spin.setSingleStep(0.001)
    quantile_spin.setDecimals(3)
    quantile_spin.setValue(0.999)
    min_pixel_spin = QDoubleSpinBox()
    min_pixel_spin.setRange(0.0, 1_000_000.0)
    min_pixel_spin.setDecimals(3)
    min_pixel_spin.setValue(0.1)

    # Feature/model controls
    category_list = QListWidget()
    category_list.itemChanged.connect(lambda _item: _refresh_feature_selection())
    feature_count_label = QLabel("Selected features: 0")
    validate_button = QPushButton("Validate feature table/dictionary")
    validate_button.clicked.connect(_validate_inputs)
    model_type_combo = QComboBox()
    model_type_combo.addItems(["auto", "hist_gradient_boosting", "random_forest"])
    train_button = QPushButton("Train/retrain classifier")
    train_button.clicked.connect(_train_model)
    apply_current_button = QPushButton("Apply classifier to current ROI")
    apply_current_button.clicked.connect(_apply_model_current_roi)
    apply_all_button = QPushButton("Apply classifier to all ROIs")
    apply_all_button.clicked.connect(_apply_model_all_rois)
    model_file_input = QLineEdit(str(model_path or ""))
    load_model_button = QPushButton("Load previous model")
    load_model_button.clicked.connect(_load_previous_model)
    save_model_button = QPushButton("Save model")
    save_model_button.clicked.connect(_save_model)
    model_status_label = QLabel("Model: not loaded")
    model_status_label.setWordWrap(True)

    # Label controls
    annotation_mode_group = QButtonGroup(getattr(viewer.window, "_qt_window", None))
    annotation_mode_widget = QWidget()
    annotation_mode_layout = QVBoxLayout()
    annotation_mode_layout.setContentsMargins(0, 0, 0, 0)
    annotation_mode_widget.setLayout(annotation_mode_layout)
    annotation_modes = ["inspect only", "flag as good", "flag as artifact", "erase flagged label", "remove any label"]
    annotation_mode_buttons = {}
    annotation_shortcut_inputs = {}
    annotation_shortcuts = {}
    default_annotation_shortcuts = {
        "inspect only": "I",
        "flag as good": "G",
        "flag as artifact": "A",
        "erase flagged label": "E",
        "remove any label": "R",
    }
    for index, mode in enumerate(annotation_modes):
        radio = QRadioButton(mode)
        annotation_mode_group.addButton(radio)
        annotation_mode_layout.addWidget(radio)
        annotation_mode_buttons[mode] = radio
        if index == 0:
            radio.setChecked(True)

    shortcut_widget = QWidget()
    shortcut_layout = QVBoxLayout()
    shortcut_layout.setContentsMargins(0, 0, 0, 0)
    shortcut_widget.setLayout(shortcut_layout)
    for mode in annotation_modes:
        row_widget = QWidget()
        row_layout = QHBoxLayout()
        row_layout.setContentsMargins(0, 0, 0, 0)
        row_widget.setLayout(row_layout)
        row_layout.addWidget(QLabel(mode))
        shortcut_input = QLineEdit(default_annotation_shortcuts[mode])
        shortcut_input.setMaximumWidth(80)
        annotation_shortcut_inputs[mode] = shortcut_input
        row_layout.addWidget(shortcut_input)
        shortcut_layout.addWidget(row_widget)
    apply_shortcuts_button = QPushButton("Apply annotation shortcuts")
    apply_shortcuts_button.clicked.connect(_apply_annotation_shortcuts)

    clicked_cell_label = QLabel("Clicked cell: none")
    clicked_cell_label.setWordWrap(True)
    confirmed_layers_visible_checkbox = QCheckBox("Show Confirmed layers when loading ROI")
    confirmed_layers_visible_checkbox.setChecked(True)
    flagged_layers_visible_checkbox = QCheckBox("Show Flagged layers when loading ROI")
    flagged_layers_visible_checkbox.setChecked(True)
    probability_layer_visible_checkbox = QCheckBox("Show Probability layer when loading ROI")
    probability_layer_visible_checkbox.setChecked(True)
    all_cells_layer_visible_checkbox = QCheckBox("Show All_cells layer when loading ROI")
    all_cells_layer_visible_checkbox.setChecked(False)
    dna_layer_visible_checkbox = QCheckBox("Show DNA image when loading ROI")
    dna_layer_visible_checkbox.setChecked(True)
    confirmed_good_contour_spin = QSpinBox()
    confirmed_good_contour_spin.setRange(0, 20)
    confirmed_good_contour_spin.setValue(0)
    confirmed_good_contour_spin.valueChanged.connect(lambda _value: _update_label_layers_display())
    confirmed_artifact_contour_spin = QSpinBox()
    confirmed_artifact_contour_spin.setRange(0, 20)
    confirmed_artifact_contour_spin.setValue(0)
    confirmed_artifact_contour_spin.valueChanged.connect(lambda _value: _update_label_layers_display())
    flagged_good_contour_spin = QSpinBox()
    flagged_good_contour_spin.setRange(0, 20)
    flagged_good_contour_spin.setValue(2)
    flagged_good_contour_spin.valueChanged.connect(lambda _value: _update_label_layers_display())
    flagged_artifact_contour_spin = QSpinBox()
    flagged_artifact_contour_spin.setRange(0, 20)
    flagged_artifact_contour_spin.setValue(2)
    flagged_artifact_contour_spin.valueChanged.connect(lambda _value: _update_label_layers_display())
    confirm_flagged_button = QPushButton("Confirm flagged labels")
    confirm_flagged_button.clicked.connect(_confirm_flagged)
    clear_flagged_button = QPushButton("Clear flagged labels")
    clear_flagged_button.clicked.connect(_clear_flagged)
    undo_button = QPushButton("Undo last annotation")
    undo_button.clicked.connect(_undo_last_annotation)

    # Bulk flag controls
    lower_threshold_spin = QDoubleSpinBox()
    lower_threshold_spin.setRange(0.0, 1.0)
    lower_threshold_spin.setSingleStep(0.01)
    lower_threshold_spin.setDecimals(3)
    lower_threshold_spin.setValue(0.1)
    upper_threshold_spin = QDoubleSpinBox()
    upper_threshold_spin.setRange(0.0, 1.0)
    upper_threshold_spin.setSingleStep(0.01)
    upper_threshold_spin.setDecimals(3)
    upper_threshold_spin.setValue(0.9)
    max_bulk_spin = QSpinBox()
    max_bulk_spin.setRange(0, 1000000)
    max_bulk_spin.setValue(200)
    avoid_confirmed_checkbox = QCheckBox("Avoid overwriting confirmed labels")
    avoid_confirmed_checkbox.setChecked(True)
    exclude_flagged_checkbox = QCheckBox("Exclude already flagged cells")
    exclude_flagged_checkbox.setChecked(True)
    flag_low_button = QPushButton("Flag low-score cells as good")
    flag_low_button.clicked.connect(lambda: _bulk_flag(FLAGGED_GOOD))
    flag_high_button = QPushButton("Flag high-score cells as artifact")
    flag_high_button.clicked.connect(lambda: _bulk_flag(FLAGGED_ARTIFACT))

    # Export controls
    export_rule_combo = QComboBox()
    export_rule_combo.addItems(
        [
            EXPORT_CONFIRMED_ARTIFACTS,
            EXPORT_CONFIRMED_AND_FLAGGED_ARTIFACTS,
            EXPORT_CLASSIFIER_THRESHOLD,
            EXPORT_COMBINED,
        ]
    )
    export_threshold_spin = QDoubleSpinBox()
    export_threshold_spin.setRange(0.0, 1.0)
    export_threshold_spin.setSingleStep(0.01)
    export_threshold_spin.setDecimals(3)
    export_threshold_spin.setValue(0.8)
    relabel_export_checkbox = QCheckBox("Relabel exported masks")
    relabel_export_checkbox.setChecked(False)
    export_current_button = QPushButton("Export cleaned mask for current ROI")
    export_current_button.clicked.connect(_export_current_roi)
    export_all_button = QPushButton("Export cleaned masks for all ROIs")
    export_all_button.clicked.connect(_export_all_rois)

    # Status/logging controls
    summary_label = QLabel("Current ROI: none")
    summary_label.setWordWrap(True)
    status_box = QTextEdit()
    status_box.setReadOnly(True)
    status_box.setMinimumHeight(220)
    traffic_light_widget = QWidget()
    traffic_light_layout = QVBoxLayout()
    traffic_light_layout.setContentsMargins(0, 0, 0, 0)
    traffic_light_widget.setLayout(traffic_light_layout)
    traffic_light_labels = {}
    for key, text in [
        ("flagged", "Flagged labels pending confirmation: not checked"),
        ("classifier", "Classifier freshness: not checked"),
        ("current_roi_score", "Current ROI score: not checked"),
        ("all_scored", "Current classifier applied to ROIs: not checked"),
        ("all_pos_neg", "ROIs with confirmed good and artifact labels: not checked"),
        ("all_reviewed", "ROIs reviewed with current classifier: not checked"),
    ]:
        label = QLabel(text)
        label.setWordWrap(True)
        traffic_light_labels[key] = label
        traffic_light_layout.addWidget(label)

    dock_panels = {
        "Controls": _build_dock_panel(
            [
                QLabel("Masks folder"),
                masks_folder_input,
                browse_masks_button,
                QLabel("Images folder(s); separate multiple with ';'"),
                images_folder_input,
                browse_images_button,
                QLabel("Feature table"),
                feature_table_input,
                browse_feature_table_button,
                QLabel("Feature dictionary CSV"),
                feature_dictionary_input,
                browse_feature_dictionary_button,
                QLabel("Output/QC folder"),
                output_folder_input,
                browse_output_button,
                QLabel("ROI column"),
                roi_column_input,
                QLabel("Object/label ID column"),
                object_column_input,
                reload_inputs_button,
                QLabel("Select ROI"),
                roi_selector,
                previous_roi_button,
                next_roi_button,
                load_roi_button,
                save_roi_button,
                reload_roi_state_button,
            ]
        ),
        "Images": _build_dock_panel(
            [
                QLabel("Image channel"),
                image_channel_selector,
                QLabel("Normalize intensity quantile"),
                quantile_spin,
                QLabel("Minimum pixel value"),
                min_pixel_spin,
                load_selected_image_button,
                load_all_images_button,
            ]
        ),
        "Labels": _build_dock_panel(
            [
                QLabel("Current annotation mode"),
                annotation_mode_widget,
                QLabel("Annotation mode shortcuts"),
                shortcut_widget,
                apply_shortcuts_button,
                clicked_cell_label,
                QLabel("Initial layer visibility"),
                confirmed_layers_visible_checkbox,
                flagged_layers_visible_checkbox,
                probability_layer_visible_checkbox,
                all_cells_layer_visible_checkbox,
                dna_layer_visible_checkbox,
                QLabel("Confirmed good contour"),
                confirmed_good_contour_spin,
                QLabel("Confirmed artifact contour"),
                confirmed_artifact_contour_spin,
                QLabel("Flagged good contour"),
                flagged_good_contour_spin,
                QLabel("Flagged artifact contour"),
                flagged_artifact_contour_spin,
                confirm_flagged_button,
                clear_flagged_button,
                undo_button,
            ]
        ),
        "Bulk flagging": _build_dock_panel(
            [
                QLabel("Lower artifact_probability threshold"),
                lower_threshold_spin,
                flag_low_button,
                QLabel("Upper artifact_probability threshold"),
                upper_threshold_spin,
                flag_high_button,
                QLabel("Maximum cells to add; 0 means no limit"),
                max_bulk_spin,
                avoid_confirmed_checkbox,
                exclude_flagged_checkbox,
            ]
        ),
        "Feature model": _build_dock_panel(
            [
                QLabel("Feature categories used for training"),
                category_list,
                feature_count_label,
                validate_button,
                QLabel("Model type"),
                model_type_combo,
                train_button,
                apply_current_button,
                apply_all_button,
                QLabel("Model file"),
                model_file_input,
                load_model_button,
                save_model_button,
                model_status_label,
            ]
        ),
        "Export": _build_dock_panel(
            [
                QLabel("Exclusion rule"),
                export_rule_combo,
                QLabel("Classifier export threshold"),
                export_threshold_spin,
                relabel_export_checkbox,
                export_current_button,
                export_all_button,
            ]
        ),
        "Status": _build_dock_panel([traffic_light_widget, summary_label, status_box]),
    }
    dock_order = ["Controls", "Images", "Labels", "Bulk flagging", "Feature model", "Export", "Status"]
    dock_widgets = {}

    def _show_dock(dock_name: str):
        dock_widget = dock_widgets.get(dock_name)
        dock_panel = dock_panels[dock_name]
        qt_window = getattr(viewer.window, "_qt_window", None)
        if dock_widget is not None:
            current_panel = dock_widget.widget()
            if current_panel is not None:
                current_panel.setParent(None)
                dock_panel = current_panel
                dock_panels[dock_name] = current_panel
            if qt_window is not None:
                qt_window.removeDockWidget(dock_widget)
            dock_widget.deleteLater()

        dock_widget = viewer.window.add_dock_widget(dock_panel, name=dock_name, area="right")
        dock_widget.setFloating(True)
        dock_widget.setVisible(True)
        dock_widget.show()
        dock_widgets[dock_name] = dock_widget
        return dock_widget

    def _show_all_docks() -> None:
        for dock_name in dock_order:
            _show_dock(dock_name)

    panel_launcher_widget = QWidget()
    panel_launcher_layout = QVBoxLayout()
    panel_launcher_widget.setLayout(panel_launcher_layout)
    panel_launcher_layout.addWidget(QLabel("Open or restore QC panels:"))
    open_all_button = QPushButton("Open all panels")
    open_all_button.clicked.connect(_show_all_docks)
    panel_launcher_layout.addWidget(open_all_button)
    dock_launcher_buttons = {}
    for dock_name in dock_order:
        button = QPushButton(f"Open {dock_name}")
        button.clicked.connect(lambda checked=False, dock_name=dock_name: _show_dock(dock_name))
        panel_launcher_layout.addWidget(button)
        dock_launcher_buttons[dock_name] = button
    panel_launcher_layout.addStretch(1)
    panel_launcher_dock = viewer.window.add_dock_widget(panel_launcher_widget, name="Panels", area="left")
    panel_launcher_dock.setFeatures(panel_launcher_dock.features() & ~QDockWidget.DockWidgetClosable)

    handles = SimpleNamespace(
        state=state,
        roi_selector=roi_selector,
        image_channel_selector=image_channel_selector,
        category_list=category_list,
        annotation_shortcut_inputs=annotation_shortcut_inputs,
        apply_annotation_shortcuts=_apply_annotation_shortcuts,
        traffic_light_labels=traffic_light_labels,
        confirmed_layers_visible_checkbox=confirmed_layers_visible_checkbox,
        flagged_layers_visible_checkbox=flagged_layers_visible_checkbox,
        probability_layer_visible_checkbox=probability_layer_visible_checkbox,
        all_cells_layer_visible_checkbox=all_cells_layer_visible_checkbox,
        dna_layer_visible_checkbox=dna_layer_visible_checkbox,
        confirmed_good_contour_spin=confirmed_good_contour_spin,
        confirmed_artifact_contour_spin=confirmed_artifact_contour_spin,
        flagged_good_contour_spin=flagged_good_contour_spin,
        flagged_artifact_contour_spin=flagged_artifact_contour_spin,
        load_inputs=_load_inputs_from_controls,
        load_roi=_load_roi,
        save_current_roi_state=_save_current_roi_state,
        train_model=_train_model,
        apply_model_current_roi=_apply_model_current_roi,
        apply_model_all_rois=_apply_model_all_rois,
        export_current_roi=_export_current_roi,
        show_dock=_show_dock,
        show_all_docks=_show_all_docks,
        dock_widgets=dock_widgets,
        dock_launcher_buttons=dock_launcher_buttons,
        panel_launcher_dock=panel_launcher_dock,
    )

    _apply_annotation_shortcuts(silent=True)
    _load_inputs_from_controls()
    if model_path:
        _load_previous_model()
    if roi_selector.count() > 0:
        if initial_roi and roi_selector.findText(initial_roi) >= 0:
            roi_selector.setCurrentText(initial_roi)
        _load_roi(roi_selector.currentText())

    napari.run()
    return viewer, handles


def main() -> None:
    parser = argparse.ArgumentParser(description="Napari active-learning QC for CellPose IMC masks.")
    parser.add_argument("--masks", default="masks", help="Folder containing one mask TIFF per ROI.")
    parser.add_argument("--images", default="images", help="Images folder. Use ';' to separate multiple folders.")
    parser.add_argument("--features", default=None, help="Precomputed feature table CSV/parquet.")
    parser.add_argument("--dictionary", default=None, help="Feature column dictionary CSV.")
    parser.add_argument("--output", default="qc_classifier", help="QC output folder.")
    parser.add_argument("--roi-column", default="ROI", help="ROI identifier column in the feature table.")
    parser.add_argument("--object-column", default="ObjectNumber", help="Mask label/object ID column in the feature table.")
    parser.add_argument("--initial-roi", default=None, help="ROI to load first.")
    parser.add_argument("--model", default=None, help="Saved classifier .joblib to load.")
    args = parser.parse_args()
    image_folders = [folder for folder in str(args.images).split(";") if folder]
    napari_cellpose_qc_active_learning(
        masks_folder=args.masks,
        image_folders=image_folders,
        feature_table_path=args.features,
        feature_dictionary_path=args.dictionary,
        output_folder=args.output,
        roi_column=args.roi_column,
        object_column=args.object_column,
        initial_roi=args.initial_roi,
        model_path=args.model,
    )


if __name__ == "__main__":
    main()
